### ISSUE TITLE
It doesn't work on spotify

### ISSUE THREAD

**Issue by MartinDelille** [docterd/MusaicFM#1]
After connecting my account, I have just a black screen, no artwork displayed.

**Comment by docterd** [comment]
Hey, do you have saved albums on Spotify? I'm currently in vacation. I will check it out, when I'm back.

**Comment by MartinDelille** [comment]
Yes I do. I must precise that I have a *Plugin blocked* message in the middle of the black screen. I guess it is a matter of authorization. There is no hurry anyway, have a good vacation ;-)

**Comment by RohitJacob** [comment]
Bumping up this request. I see the same black screen

**Comment by docterd** [comment]
Hey. Can you check some stuff for me? 
How many Albums did you save on Spotify. Is the Last.fm part working? With macOS version are you using?

**Comment by RohitJacob** [comment]
Around 40 albums, running on El Capitan. Looks like El Capitan is the issue because it's working on my Sierra.

**Comment by docterd** [comment]
Okay. Unfortunately I don't own a El Capitan computer anymore. I will probably bump up the version since I can't support it.

**Comment by MartinDelille** [comment]
Since I still under El Capitan, I'll be happy to try to fix this but I have no experience with screen saver development. I cloned the project and opened it with XCode but how can I launch the app in debug mode?

**Comment by MartinDelille** [comment]
In fact I have an error linking SDWebImage. Is there something to do with the Podfile?

**Comment by docterd** [comment]
Hey,
No, the Podfile should be fine. It's important that you don't use Frameworks, because everything needs to be contained in the binary. 

To test the Screensaver you need to disable SIP. In your build config specify to use the ScreenSaverEngine. (/System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app/Contents/MacOS)

**Comment by MartinDelille** [comment]
I finally migrate to 10.12 and the problem is solved!
