### ISSUE TITLE
Last.fm albums with no artwork are being shown.

### ISSUE THREAD

**Issue by daniel-stoneuk** [docterd/MusaicFM#10]
This issue only occurs on Last.fm. I assume this is because Spotify always returns album artwork and Last.fm does not. 

See the attached screenshot for an example of empty slots when using Last.fm top albums. Can these slots either be prioritised for artwork updates or retried upon first loading.

<img width="1280" alt="Screenshot 2019-05-28 at 19 32 20" src="https://user-images.githubusercontent.com/15860949/58503020-a7f21280-817f-11e9-87a9-02b735fe6e2b.png">

Thanks for the work on such a cool screensaver!

**Comment by docterd** [comment]
Yes indeed. Last.fm Image catalogue is not as rich as from Spotify. I can take a look at adding this feature, when I got time.

**Comment by docterd** [comment]
Try out 1.1.3. It should fix this issue.

**Comment by daniel-stoneuk** [comment]
Yep, perfect. Thanks very much. Will also update the homebrew repo.
