### ISSUE TITLE
MacOS Catalina

### ISSUE THREAD

**Issue by aleaidan** [docterd/MusaicFM#18]
Hey just updated to mac os catalina and it doesn't let me change the screen saver options and its displaying random albums, just letting you know

**Comment by docterd** [comment]
Hey, thanks for reporting that issue. I saw that you forked the project. You want to check it out?

**Comment by aleaidan** [comment]
Oh I did that by accident and I have no idea what it means, I made a github just to let you know about the Catalina thing.

**Comment by lucasrodcosta** [comment]
Same here.

I just found [this thread](https://www.reddit.com/r/MacOS/comments/cgj1qs/cant_be_opened_because_apple_cannot_check_it_for) on Reddit about this.

Looks like it's a good idea _notarize_ the app to avoid the issue:
https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by aleaidan** [comment]
I was able to download it again and it works, except I was logged out of my lastfm account and nothing happens when I pressed the screen saver options button.  I don’t think its because it isn’t notarized though.

**Comment by docterd** [comment]
Hey. Can you check this build? 
http://droplr.obrhoff.de/RbcLsl

**Comment by AndrewRobinson1** [comment]
Hi there, coming in here because I have the same issue. When I try to launch the build I get an error saying “MusaicFM.saver” can’t be opened because Apple cannot check it for malicious software. So, unfortunately, I can't test.
![image](https://user-images.githubusercontent.com/56349055/66479154-e7076d00-ea69-11e9-9a2e-61a45b70898c.png)

**Comment by docterd** [comment]
Sorry. This build should be better. http://droplr.obrhoff.de/MauD9O

**Comment by dnimishe** [comment]
I got the same error that the other person got about it not being able to be checked for malicious software

**Comment by AndrewRobinson1** [comment]
Same thing unfortunately

**Comment by RamiroAuditore** [comment]
Just here to confirm that I also have this problem

**Comment by docterd** [comment]
Okay this package should be notarized properly. There is still a Issue with the preference pane that I need to check out. http://droplr.obrhoff.de/4vD1Za

**Comment by docterd** [comment]
Okay problems should be solved now with 1.1.5.

**Comment by lowking** [comment]
> Okay problems should be solved now with 1.1.5.

brew cask install musaicfm is 1.1.4

**Comment by docterd** [comment]
Please update your branch. It's definitely there. 

https://github.com/Homebrew/homebrew-cask/blob/3c43b1fde0d51851aac1f1bc1a78bdc4a423e8ce/Casks/musaicfm.rb
