### ISSUE TITLE
won't work on MacOS 10.11.6

### ISSUE THREAD

**Issue by emjayking** [docterd/MusaicFM#2]
After installing the screensaver I am unable to view it's settings in order to sign in to my spotify and get it to work. I have tried uninstalling and reinstalling etc. As stated in the title this is on MacOS 10.11.6, I have tried it on another mac running OS 10.14.2 and it works like a charm (although I wish it would show what I am currently playing but hey, beggars can't be choosers.) So is there any workaround I can do to get it working on the old OS or not? if not then no worries

**Comment by docterd** [comment]
Unfortunately I don't have 10.11 available to try. I will probably bump up the supported MacOS version to 10.12, if older version are not working.
