### ISSUE TITLE
Catalina issues

### ISSUE THREAD

**Issue by efcboy** [docterd/MusaicFM#21]
Downloaded through the link below but still having issues on Catalina. [Screensaver shows up as black screen and the options button is greyed out](https://i.imgur.com/A7o79JK.png)

**Comment by docterd** [comment]
I incidentally revoked my Certificates on developer.apple.com. I guess that's the reason why App Notarization is a bad thing.

**Comment by docterd** [comment]
Can you check if this build is working again?
[MusaicFM.saver.zip](https://github.com/docterd/MusaicFM/files/4074739/MusaicFM.saver.zip)

**Comment by efcboy** [comment]
It works! But now having issues with Spotify log in. [After logging into my Spotify there's no way to exit](https://i.imgur.com/lwo64PZ.png) and if I click done, [the screensaver doesn't update to my Spotify library.](https://i.imgur.com/a4M9Ve3.png)

**Comment by docterd** [comment]
Please open another issue, since this is not related with the recent build issue.

**Comment by docterd** [comment]
Okay I just broke the above posted binary. I just rebuild the whole thing and will update now the binary of the release. Thanks for reporting.
