### ISSUE TITLE
Spotify Log In Issue

### ISSUE THREAD

**Issue by efcboy** [docterd/MusaicFM#22]
Having issues with Spotify trying to log in. [After logging into my Spotify there's no way to exit](https://i.imgur.com/lwo64PZ.png) and if I click done, [the screensaver doesn't update to my Spotify library.](https://i.imgur.com/a4M9Ve3.png)

**Comment by AndrewRobinson1** [comment]
Hey, I believe this is an issue with Spotify at the moment and Facebook logins, so maybe try signing in with your email? Sorry if this is no help, I just had an issue with Spotify and Facebook earlier today

**Comment by efcboy** [comment]
Thanks for the advice, all working through the facebook log in now!
