### ISSUE TITLE
Screen Saver Options

### ISSUE THREAD

**Issue by sabm1** [docterd/MusaicFM#26]
Hi! I'm having issues with opening the screen saver options to log into my Spotify because when I press it nothing opens. I tried re-downloading and it didn't work

**Comment by docterd** [comment]
I tried a fresh install on Catalina on a friends device and it worked. (installed through homebrew). Can you give me some more information about your setup? Which macOS version are you using?

**Comment by wkey34** [comment]
Hi,
I'm having this issue too. I am on macOS Catalina 10.15.7 and I have tried installing through both homebrew and downloading the files and neither have worked. The program worked before but stopped approximately 2 weeks ago.

**Comment by docterd** [comment]
Can you try out this WIP build? [MusaicFM.saver.zip](https://github.com/docterd/MusaicFM/files/5314562/MusaicFM.saver.zip)

**Comment by wkey34** [comment]
> Can you try out this WIP build? [MusaicFM.saver.zip](https://github.com/docterd/MusaicFM/files/5314562/MusaicFM.saver.zip)

I'm getting the same issues

**Comment by docterd** [comment]
Can you guys try following steps? The error happened me too. There seems to be a related issue on the Aerial screensaver. [#873](https://github.com/JohnCoates/Aerial/issues/873)

- delete the ScreenSaver
- Delete everything related in `~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences`
- Reinstall the Screensaver

**Comment by wkey34** [comment]
> Can you guys try following steps? The error happened me too. There seems to be a related issue on the Aerial screensaver. [#873](https://github.com/JohnCoates/Aerial/issues/873)
> 
> * delete the ScreenSaver
> * Delete everything related in `~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences`
> * Reinstall the Screensaver
> 
> **Edit**: Another preview version which also hopefully fixes the issue. [1.2 Beta](https://github.com/docterd/MusaicFM/files/5321868/MusaicFM.saver.zip)

That's working for me now, thank you for the help!
