### ISSUE TITLE
Artists screen saver shown empty

### ISSUE THREAD

**Issue by dotrachit** [docterd/MusaicFM#27]
## Problem
All my screen saver options are working apart from the **Artists** option. Instead of showing an error message, the screen remains empty.

![image](https://user-images.githubusercontent.com/44428198/94427601-fb79d380-01ac-11eb-8de3-8a1f63735e57.png)

## Picture
![image](https://user-images.githubusercontent.com/44428198/94428150-da65b280-01ad-11eb-851c-789542d94667.png)

**Comment by docterd** [comment]
Can you guys try following steps?

- delete the ScreenSaver
- Delete everything related in `~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences`
- Reinstall the Screensaver

**Comment by docterd** [comment]
API seems to be broken. I will remove the option in the upcoming 1.2 release.
