### ISSUE TITLE
version numbers don't match

### ISSUE THREAD

**Issue by core-code** [docterd/MusaicFM#28]
i've downloaded version 1.2 from GitHub but after download it claims to still be at version 1.1.6
<img width="258" alt="Screenshot 2020-10-29 at 11 52 47" src="https://user-images.githubusercontent.com/1261954/97559147-589bbb80-19dd-11eb-8b69-c56ffcaece87.png">

the CFBundleShortVersionString in the Info.plist doesn't line-up with the release version

**Comment by docterd** [comment]
Thanks! I forgot to bump that.

**Comment by docterd** [comment]
I resolved this problem with the latest release. Thanks for reporting.

**Comment by core-code** [comment]
thanks, i can confirm the problem is resolved!
