### ISSUE TITLE
Stopped working after Spotify reset my password

### ISSUE THREAD

**Issue by edwardleardi** [docterd/MusaicFM#29]
Installed this a couple of days ago and added my Spotify account and everything worked until today when I got an email from Spotify to reset my password:

> To protect your Spotify account, we've reset your password due to detected suspicious activity.

After resetting, the screen saver no longer works. Also, when I try to click "Screen Saver Options" within "Desktop & Screen Saver" preferences, the options page no longer pops up. I tried deleting and redownloading, and I also tried revoking the app's access on Spotify's website.

**Comment by docterd** [comment]
Hi, thanks for reporting. I will probably disable Spotify in the Preview in future to handle this situation. (It will then always display the default account in the Preferences Preview).

**Comment by docterd** [comment]
Can you check this build? it should handle the invalid token now right. You still need to Sign out/in to Spotify in the Preferences.

[MusaicFM.saver.zip](https://github.com/docterd/MusaicFM/files/5790504/MusaicFM.saver.zip)

**Comment by docterd** [comment]
Should be fixed with the latest release. Reopen if needed.

**Comment by edwardleardi** [comment]
Seems to work again, thanks!
