### ISSUE TITLE
Homebrew Install

### ISSUE THREAD

**Issue by 1sdc0d3r** [docterd/MusaicFM#30]
brew cask is now depreciated. Please update the readme to say "brew install --cask musaicfm"

**Comment by docterd** [comment]
Feel free to open a PR.

**Comment by 1sdc0d3r** [comment]
Will do, thank you.

**Comment by 1sdc0d3r** [comment]
I am getting an error: Git: "Permission to docterd/MusaicFM.git denied to 1sdc0d3r."

**Comment by docterd** [comment]
It's not possible for you to push directly into this repository, since only the owner can do this (me). No worry about the fix. @MartinDelille already got it covered.

**Comment by docterd** [comment]
You can't push directly into the repository since only the owner can do that (me). No worries about the issue. @MartinDelille  already got it fixed.

**Comment by 1sdc0d3r** [comment]
Ok, how do I it for in the future?

Thank you,
Braden Bell

**Comment by MartinDelille** [comment]
@1sdc0d3r Here is a guide explaining how to fork project in order to contribute to it: https://guides.github.com/activities/forking/
