### ISSUE TITLE
Library album artwork

### ISSUE THREAD

**Issue by markomitranic** [docterd/MusaicFM#40]
Would it be possible to add a "Library albums" option for Spotify?
For example I have an extensive library, however most of them I've never "liked", so they will never appear in the screensaver.

**Comment by obrhoff** [comment]
That makes sense. I will take a look, when I got the time.

**Comment by HaivanJV** [comment]
And would it be possible to do the same by selecting specific playlists from the Library?
Thank you! great project

**Comment by richpodraza** [comment]
@markomitranic, how are these albums associated with your Library if you have not "liked" them? Are they in playlists you created?

**Comment by markomitranic** [comment]
@richpodraza @obrhoff I understand how my original message may be confusing, sorry about that. Here is a nice illustration:

<img width="164" alt="Skærmbillede 2023-04-14 kl  13 06 29" src="https://user-images.githubusercontent.com/10811624/232028165-c23be776-c72d-4e5c-8a22-1ed2caafea5a.png">

⬆️  This is the current options we have. We don't have one for "Liked Albums".

AFAIK "Liked Songs" is not the same as "Liked Albums". I like a lot of albums (in order to add them to my library), but individual songs are not liked within them as that honour only goes to the individual songs i love the most. So, my library is full of liked albums I listen to, not individually liked songs. In fact, this option would be the closest thing we can get, to having an experience similar to Apple's Music Screensaver, which only displays cover art of "albums in your library".

There is an option to have "Played Albums" but that is not the same as "Liked Albums". I play a lot of albums, not all of them I like :D

**Comment by richpodraza** [comment]
@markomitranic I am ofc not the author, but I am somewhat familiar with the Spotify API. I don't think Spotify has a public API to see albums you have played, only albums you have saved/liked (i.e. the green heart). If I'm right, this setting should be renamed to "Saved Albums" or something like that. FWIW from what I can see, the Played Albums options appears to show my saved albums, but obviously most albums I've saved I've also played...

Otherwise I would be very interested to learn from @obrhoff how he's getting "played albums" because I don't think that's possible!

Anyway I suggest in the short term, try out the "Played Albums" options and see if it correlates to your liked albums in Spotify.

**Comment by obrhoff** [comment]
Hi,

I think we fetch through latest played tracks and grab out the parent album out of it.

**Comment by markomitranic** [comment]
Thanks for the tip @richpodraza I will try it out and report findings.

@obrhoff oh ok sorry to hear that. Do you think it would be feasible to introduce the Liked Albums functionality then?

**Comment by obrhoff** [comment]
Tbh I need to look again into the implementation. I might just have named it wrong 😅

**Comment by markomitranic** [comment]
@obrhoff [Spotify says](https://developer.spotify.com/documentation/web-api/reference/get-users-saved-albums) that this endpoint corresponds to "Users Saved Albums" in "user's Your Library". 

Just looking at your code (without knowing Swift) it looks like you are using the "Saved Albums" api endpoint, which would mean that the label is just wrong.

P.S. How many items do you fetch? I assume you don't fetch the whole library?

**Comment by obrhoff** [comment]
It fetches the whole album library and caches it locally.
