### ISSUE TITLE
Unable to log into Spotify

### ISSUE THREAD

**Issue by markomitranic** [docterd/MusaicFM#41]
Hey there, 

as of recently, I got a new machine, M1, and installed Musaic. When the auth window for spotify opens, I am able to interact with it and log in, but not able to click the green Allow button. When I do, nothing simply happens.

**Comment by WillDickson380** [comment]
Same problem as me.

**Comment by obrhoff** [comment]
Hey, are you sure you got the newest version? It sounds like this issue which already got fixed. https://github.com/obrhoff/MusaicFM/issues/39

**Comment by WillDickson380** [comment]
Hi, I meant to add- its been fixed now... I just had to keep trying and then it worked eventually. Yes, I might not have the latest version.
