### ISSUE TITLE
Screen saver (and preview) is blank, but thumbnail looks correct

### ISSUE THREAD

**Issue by richpodraza** [docterd/MusaicFM#44]
I am on macos 13.3.1 (22E261) MusaicFM 1.2.5 installed via homebrew. I also have multiple monitors, 2 external plus the MBP display. 

No problems signing in to Spotify. When the screen saver comes on, or when I force it on with the Preview button, it is just blank. No CD icon (like I've seen in other closed issues), just a totally black screen.

BUT, the thumbnail it shows in the screen saver Options menu does show album art and I can tell they are mine, they are all albums saved in my Spotify account. See this example:
![image](https://user-images.githubusercontent.com/22397411/231511639-7a999988-d8b4-42f4-bc35-60fd01a0a5a8.png)

Any ideas?

**Comment by richpodraza** [comment]
I suppose I should have tried this earlier, but the problem goes away if I unplug the external monitors. If the laptop Built-in Display is the only display, things look as expected.

My normal setup is with the Built-in Display as the Main Display at 2048x1280 and two external monitors (same model, Sceptre Q27) both as Extended displays at 2560x1440.

On a hunch I changed my Built-in Display to mirror one of the external monitors. With this setup, the screen saver does display, but only on the "main" external display. The built-in display doesn't show the screen saver (a bit surprising since it is mirroring the main display) and the other external monitor doesn't show the screen saver.

**Comment by obrhoff** [comment]
You don't have a problem with other screensavers right? I will check later if I got the same issue here (MacBook ans Apple Studio Display). But I remember it used to work with multiple displays.

**Comment by richpodraza** [comment]
Yeah I've used at least 2 of the macos screen savers and they do fine across my display setup

**Comment by alagos** [comment]
Didn't notice this issue was created, but my comment here https://github.com/obrhoff/MusaicFM/issues/47#issuecomment-1540893103 is relevant.

**Comment by Row** [comment]
Have the same or related issue. With external screens, extended desktop and osx Ventura 13.3.1 the mosaic is only rendered on one of the external screens in the bottom left half of the screen, seems to have the same proportion as the laptop screen.

update: It seems to work on OSX 13.5

**Comment by alagos** [comment]
@obrhoff I second Row's comment, I'm using 13.5.2 and this doesn't seem to an issue anymore, so probably the Apple team already fixed it.
