### ISSUE TITLE
Mouse hover support?

### ISSUE THREAD

**Issue by kurt-wink** [docterd/MusaicFM#46]
One thing I enjoyed about the original macOS screensaver was the ability to move your mouse over each album's artwork to play it. An improvement on this would be to show the album name and artist upon hovering too.

Thanks for making such an awesome screensaver! 😁

**Comment by Cookdao** [comment]
Same！
Can we click and play it on spotify 
much appreciate！

**Comment by obrhoff** [comment]
Afaik its not really possible with the Screensaver API.
