### ISSUE TITLE
Screensaver doesn't display in all the screens for a multiple displays setup

### ISSUE THREAD

**Issue by alagos** [docterd/MusaicFM#47]
With an extra monitor connected, I'm only seeing the screensaver in a single screen

![IMG_20230509_142543](https://user-images.githubusercontent.com/475834/236978509-9b8386be-3511-43b1-9b14-e13a464051f3.jpg)
which it doesn't happen with some of the default ones
![IMG_20230509_142631](https://user-images.githubusercontent.com/475834/236978468-245d585d-56c1-41fa-9c07-18fa098f7dab.jpg)

Worth to mention, the screensaver is displayed only in the screen configured as "Extended display"
<img width="549" alt="Screenshot 2023-05-09 at 2 36 30 PM" src="https://user-images.githubusercontent.com/475834/236979661-6b79edde-0dfa-455b-8a4e-4034215cdb54.png">

if I change the external monitor (that "Dell" in the screenshot) to be the "extended" one, the behaviour also changes
![IMG_20230509_143531](https://user-images.githubusercontent.com/475834/236979787-0a7b1236-6872-46bf-a545-55be6288ee17.jpg)

I'm not quite sure when this started to fail, as not all the time I have another screen connected, but I've just upgraded to Ventura a few weeks ago, so maybe that's when all this started to fail?
Also, I've had installed 1.1.5 all these years and I've upgraded to 1.2.5 just now, but that didn't fix the problem.

**Comment by obrhoff** [comment]
I think this is a duplicate to this ticket. Unfortunately I did not had time to look into the issue (sorry but I'm super busy with work and kids ☹️ )

**Comment by alagos** [comment]
Yeah, I feel you. I'd help to debug this, but my Objective-C knowledge is near to 0 :(

**Comment by alagos** [comment]
Hmm, clearly isn't a problem exclusive to MusaicFM [but to any screensaver in Ventura](https://discussions.apple.com/thread/254745941).
I suppose there's nothing more left than waiting for an update from Apple, but I really doubt this is in their priorities.
Anyway, closing

**Comment by obrhoff** [comment]
Thanks for checking it out.
