### ISSUE TITLE
Crash with wrong LastFM name

### ISSUE THREAD

**Issue by cameron-toy** [docterd/MusaicFM#7]
I had a typo in my LastFM username and now choosing the screensaver in preferences causes the preferences pane to hang. Deleting the .saver file and reinstalling don't fix the issue.

**Comment by docterd** [comment]
Hey, thanks for reporting. I will take a look over the weekend.

**Comment by docterd** [comment]
Unfortunately I can't reproduce this issue. Can you give me the wrong used Last.fm Username?
